@startuml
allowmixing
!define RECTANGLE class

skinparam rectangle {
    BackgroundColor #e0f7fa
    BorderColor #0288d1
    FontSize 12
}
skinparam cloud {
    BackgroundColor #fff3e0
    BorderColor #ffa726
    FontSize 12
}

RECTANGLE "Client\nReact.js\nTypeScript" as FE
RECTANGLE "Webserver\nNode.js\nExpress.js\nTypeScript" as BE
cloud "Database\n(PostgreSQL)" as DB

FE -[#blue]-> BE : "REST API\nHTTPS (JSON)"
BE -[#orange]-> DB : "DB/\nORM/ODM"

@enduml